-- phpMyAdmin SQL Dump
-- version 4.7.0
-- https://www.phpmyadmin.net/
--
-- Host: 127.0.0.1
-- Generation Time: Dec 30, 2017 at 03:30 PM
-- Server version: 10.1.25-MariaDB
-- PHP Version: 5.6.31

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET AUTOCOMMIT = 0;
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `bot`
--

-- --------------------------------------------------------

--
-- Table structure for table `asset_catalog`
--

CREATE TABLE `asset_catalog` (
  `id` int(11) DEFAULT NULL,
  `innovation_area` text,
  `asset_name` text,
  `asset_summary` text,
  `asset_poc` text,
  `asset_type` text,
  `asset_keywords` text
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

--
-- Dumping data for table `asset_catalog`
--

INSERT INTO `asset_catalog` (`id`, `innovation_area`, `asset_name`, `asset_summary`, `asset_poc`, `asset_type`, `asset_keywords`) VALUES
(1, 'Semiconductor Innovation', '3D Printing + 3D Scanning platform', '3D Printer and 3D Scanner made by UST R&D team which can print objects using a CAD drawing or to replace a broken part by scanning it and printing a new one ', 'Shine Xavier ', 'MVP - Minimum Viable Product', 'semi conductor   semiconductor   3d print   3d scan   MVP - Minimum Viable Product   shine xavier   3d printer   3d printing   3d scanner   3d scanning   3D Printing + 3D Scanning platform'),
(2, 'Boots Ideathon', 'Accelerate Issue Management', 'To effectively handle incidents it is always good to primarily focus on Restoring the service ASAP rather than spending more time on RCA (Root cause Analysis) .Instead of bringing in a new system the idea is to improvise the current Service Now tool Boots make use of as part of Ticket management . The tool should be integrated with a Known error Database with search keywords or filters to retrieve relevant records to assist oncall for resolving  incidents . When an incident is logged the tool should  sent alerts to all concerned groups engaged so that each one of them with their critical problem solving skills and individual expertise can bring in faster resolutions', 'Anjaly Sreekumar', 'MVC - Minimum Viable Concept', 'boots ideathon   accelerate issue management   anjaly sreekumar   MVC - Minimum Viable Concept'),
(3, 'Machine Learning', 'Anthem chatbots', 'Customised chatbots using AI to help customers find the best providers in the location with their Contact no   Mail id with the customers rating also it shows the distance of the provider form the customer location using GPS. ', 'Chandrasekhar S Mohammed Sarfaras', 'MVP - Minimum Viable Product', 'machine learning   ML   anthem chatbots   chandrasekhar   mohammed sarfaras   MVP - Minimum Viable Product'),
(4, 'Machine Learning', 'App 360', 'App360 collects huge volumes of data from a wide variety of sources and converts them to actionable insights. These insights could power your application support eam identify and resolve issues with ease.Anomaly detection powered by Machine Learning.Real time monitoring and visualization of Machine Data.Breakdown and analyse your logs efficiently.', 'Chandrasekhar S', 'MVP - Minimum Viable Product', 'machine learning   ML   app 360   anamoly detections   chandrasekhar   MVP - Minimum Viable Product   anamolies'),
(5, 'Augmented Reality', 'AR or VR based Shopping Gamification', 'Debenhams Augmented reality app to reduce blindspots in shops by using geolocation to help find offers in a particular locations to increase footfalls in that location . Like Pokemon Go', 'RajaLakshmi Baburajan', 'MVC - Minimum Viable Concept', 'augmented reality   AR   virtual reality   VR   debenhams   rajalakshmi baburajan   MVC - Minimum Viable Concept   retail   shopping   shops   AR or VR based Shopping Gamification'),
(6, 'D3', 'AutoBots', 'Predictive proactive auto-scaler for applications with large variation in workload. Auto-scaling is a method used in cloud computing   whereby the amount of computational resources in a server farm   typically measured in terms of the number of active servers   scales automatically based on the load on the farm. \nNormal auto-scaling methods are reactive systems   which scales systems based on parameters like CPU load   Network load or memory utility. This method lacks an analytic component and can lead to undesired up or down scaling. The Autobots auto-scaler employes machine learning algorithms to address the limitations of traditional auto-scalers like Amazon Auto Scaling (AAS). \n', 'Akash Viswan', 'Product', 'd3   autobots   auto scaling   machine learning   akash viswan   Products'),
(7, 'IoT', 'Automatic Sprinkler System', 'Sprinkler system for retail to keep fruits and vegetables fresh by sprinkling water to maintain Humidity ', 'Thomas K John', 'MVP - Minimum Viable Product', 'iot   internet of things   automatic sprinkler system   thomas k john   MVP - Minimum Viable Product   agriculture   farming   fruit   vegetable   MVP - Minimum Viable Product'),
(8, 'Machine Learning', 'AutoOps ', 'AutoOps is an automation framework. It can be used to automate the workflows that are usually done by L1 support. It can interface with users through email   chat   jira   etc.', 'Chandra Ranjith Mohan Nair', 'MVP - Minimum Viable Product', 'machine learning   ML   autoops   automation   chandra   ranjith   MVP - Minimum Viable Product'),
(9, 'Bussiness Model', 'Blue Buzz', 'Our business models canvas is developed for a company who offers Blockchain as a service (BaaS) - which is a flexible and scalable platform to address operational business process   performance and security.  The company provides customers’ with end to end service in revamping their data-driven business process in to Blockchain enabled process. This helps customers to utilize Blockchain technology to its full potential by reducing fraud and streamlining business process. With our value proposition canvas   we are able to address customer fears   needs and wants with Productservices   its features and benefits   thus resulting in easy customer buy-in. ', 'Sumitha Latha   Anand Sreekumar   RamShankar  Pillai   Sini Sahadevan ', 'MVC - Minimum Viable Concept', 'business models   blue buzz   MVC - Minimum Viable Concept'),
(10, 'Boots Ideathon', 'Boost', 'Salesforce (SFDC) offers many capabilities out of the box to quickly and declaratively create an application for IT support replacing costly custom developments for this same purpose. In fact   it already offers a Cases solution which acts as a central repository to use for tracking all customer support interactions. The IT help desk ticketing process by building on CRM platform. It is much faster to set up a process to handle these tickets and to customize the Case capability already present in the tool to manage internal service requests from employees. Work can be assigned to queues and Chatter   the internal social channel   can be leveraged to collaborate on requests. Additionally everything is tracked in one single platform.', 'Antonio Elena', 'MVC - Minimum Viable Concept', 'CRM   boots ideathon   MVC - Minimum Viable Concept   boost'),
(11, 'IoT', 'Cancer Care App', '', 'Thomas K John', 'MVC - Minimum Viable Concept', 'iot   internet of things   cancer care app   health care   MVC - Minimum Viable Concept '),
(12, 'Boots Ideathon', 'Customer Case Tracking', 'Building an enterprise Case Management layer to store the reusable components and common services to access backend systems and establishing one single system to handle cases. A system to provide an avenue for customers to submit requests or issues during and after the sales process is critical to ensuring that customers are satisfied and willing to do business with your company in the future.', 'Prajosh Gopi', 'MVC - Minimum Viable Concept', 'boots ideathon   customer case tracking   MVC - Minimum Viable Concept'),
(13, 'Machine Learning', 'Customer Sentiments Insights', 'Customer Sentiment Analysis', 'Chandra', 'MVC - Minimum Viable Concept', 'machine learning   ML   sentiment analysis   sentiments analysis   MVC - Minimum Viable Concept   Customer Sentiments Insights'),
(14, 'Boots Ideathon', 'Customer Support System', 'Customer Support System assisted by Machine Learning Algorithms which identifies the user problem using NLP and associated algorithms. It derives and provide instant solutions from Centralized Knowledge management repository  once the user provides the input\n', 'Rohit Jothindran', 'MVC - Minimum Viable Concept', 'boots ideathon   machine learning   ML   NLP   natural language processing   MVC - Minimum Viable Concept   customer support system'),
(15, 'GIS Datathon', 'DevApps', 'Create a software application that will act as smart engine applying  logical analytics  to derive location related features.Benefits include Land Score Index – Land suitability can be calculated based on Slope   Floodplain   Soil classified based on restriction to construction   Sewer service   Distance to major roads etc.Location Efficiency Index – Can be calculated based on the environment data such as Density   Accessibility   Transit Service   Employment   Population   urban design etc. Location efficiency can be used as a predictor for mortgage.Location Affordability Index -  The Location Affordability Index (LAI) gives estimates of the percentage of a family s income dedicated to the combined cost of housing and transportation in a given location or at the neighborhood level to help individuals   planners   developers and policymakers make more informed decisions about where to live   work   and invest.\n\n', 'Dileep Narayanan  Ambily Umasuthan', 'MVP - Minimum Viable Product', 'gis datathon   devapps   dev apps   land   location   MVP - Minimum Viable Product'),
(16, 'GIS Datathon', 'DHTTP', 'Efficient management of Sewage water using GIS and IOT .Using the GIS data available with landmark    identifying the pipes    manholes    negative slope of the pipes and managing the water flow by adding low cost Arduino ultrasonic sensor on the manholes with the application IOT .\n', 'Subhojeet Biswas', 'MVC - Minimum Viable Concept', 'gis datathon   dhttp   sewage water   IOT   internet of things   MVC - Minimum Viable Concept   arduino'),
(17, 'Bussiness Model', 'DHTTP', 'We as an IT services organization look to add value proposition to our customer business models when then go for a mergeracquisition.\nWe suggest to integrate IT not only in the post-merger scenario but also in the pre-merger integration.\nDigging more into the solutions we revolve creating synergy based on the 4 pillars.\n• Revenue growth\n• Customer and partner experience\n• Business process efficiencies\n• Foundational programs\nWe propose ways and benefits by which our clients integrate IT in merger all through the merger process and even after that.\nAccordingly we redefine the business modal canvas with examples of our clients such as (Anthem-Cigna)and (Safeway- Albertsons) merger how we help enterprises realize more value from the operational and market synergies that bring businesses together.\n', 'Subhojeet Biswas   Sreerag Vinod   Hariesh Asokkumar    Karthick Sundaram  ', 'MVC - Minimum Viable Concept', 'business models   dhttp   MVC - Minimum Viable Concept'),
(18, 'Bussiness Model', 'DigiCanvaUS', 'We have customized the BMC by splitting the Value Proposition segment to Direct & Indirect Value Propositions   added a segment for Beneficiaries   Surplus and Influencers.\n\nBMC is customized because   Value Propositions shouldn’t just be limited to those that will earn profit for the organization   need to consider the indirect benefits as well. Added Beneficiaries because   not just the customers to be cared about while considering the service offerings. Added Surplus because   an organization should not settle down with the profits that earned   it needs to be look out for opportunities for expansion. Added Influencers because   not only the organizations policies affects it’s business models   but   there are other external factors like its competitors   Govt. policies   technological advancement also be cared about.\n', 'Rincy Thomas   Manu Raj Sathyarajan   Prasanth Sreekumar   Satya Narayana Das', 'MVC - Minimum Viable Concept', 'business models   digicanva us   digicanvaus   MVC - Minimum Viable Concept'),
(19, 'Semiconductor Innovation', 'Digital Farming Solution', 'FarmUS is digital food computer developed by UST R&D team to allow exotic plants to br grown in any climate by simulating the optimal condition for their growth by controlling various parameters like humidity    UV light etc using sensors ', 'Shine Xavier ', 'MVP - Minimum Viable Product', 'semi conductor   digital farming solution   MVP - Minimum Viable Product'),
(20, 'Public Sector', 'Digital Services Management System', 'Digital Services Management System is a platform to \n1. Manage the lifecycle of a Subscriber and subscriber clusters\n2. Manage the lifecycle of Products   devices and services that the subscribers order \n3. Manage the billing   payment and GLs for the subscriber \nDSMS has the ability to group the customers on any number of clusters for specific business objectives. It can also interface with any third party system to achieve the business objectives in a client ecosystem.\n', 'Pradeep Joseph ', 'Product', 'Digital Services Management System   public sector   Product   dbms'),
(21, 'Mobility', 'Digital Wallet', 'Mobile solution for integrating various banking functionalities and retail options.', 'Sreedevi Pillai', 'MVP - Minimum Viable Product', 'mobility   retail   MVP - Minimum Viable Product   Digital Wallet'),
(22, 'Artificial Inteligence', 'DocGraph', 'Generic content management system which gives similar   user based and personalized recommendation for multitude document and retail Products.', 'Rahul Panakkal', 'MVP - Minimum Viable Product', 'AI   artificial intelligence   retail   MVP - Minimum Viable Product   DocGraph'),
(23, 'Digital Enterprise Apps', 'Edge Connect Mobile ERP Solution', 'EdgeConnect is a project Management tool . It is expected to improve the communication and status updates among the stake holders . This will enable monitoring and addressing issues and risks on time. It also helps every member of the engagement adequately informed about the various activities. ', 'AjithLal Rijad Raheem', 'MVP - Minimum Viable Product', 'digital enterprise apps   Edge Connect Mobile ERP Solution   mobile erp   MVP - Minimum Viable Product'),
(24, 'Digital Enterprise Apps', 'Edge-Ops', 'Edge-Ops™ is the transformational solution you need for rapid and agile technological adaptation across people   process   and policies   enabling your business to “sense and respond” to your customers.', 'Anjali Nair ', 'MVP - Minimum Viable Product', 'digital enterprise apps   mobile erp   MVP - Minimum Viable Product   edgeops   edge ops   Edge-Ops'),
(25, 'Bussiness Model', 'Empresarios', 'The existing model of business models Canvas and its limitations were studied. A new model is built upon the basic concept of the existing model overcoming the limitations identified. The new proposed business models   “Layered Business Matrix” consists of 12 business elements arranged as four different business layers namely Decision   Process   Planning and Customer Layers. The new model eases the business plan considering all the basic elements and the business process flow. The model is basically designed to suit the needs of all the businesses universally', 'Madhanish Manoharan   Kiranprasath Krishnamurthy   Arunkumar Palanisamy', 'MVC - Minimum Viable Concept', 'business models   Empresarios   MVC - Minimum Viable Concept  '),
(26, 'Social', 'EXCITE News Aggregation Engine (For MiGHT   Malaysia)', 'UST Global EXCITE platform continuously scans for relevant information from a plethora of data sources   classifies and enriches data and makes it available through a responsive web application. EXCITE eliminates manual effort by 60% there by improving the Productivity of researchers. The solution leverage ICE platform to perform the categorization and sub categorization of news automatically. The list of sites to be crawled   the search terms etc. are fully configurable.\n\nBenefits\n• Drastic improvement in the researchers Productivity by automating their day to day activities\n• Quick turnaround in discovering relevant news and bringing it to researchers\n• Reusable Product that can be customized for other clients\n', 'Deepa Sobhana', 'MVP - Minimum Viable Product', 'EXCITE News Aggregation Engine (For MiGHT   Malaysia)   social   excite news aggregation   MVP - Minimum Viable Product   ICE platform'),
(27, 'Mobility', 'Facility Management App', 'UST Internal app which shows schematics of the building with Seating positions of each employee and location of all meeting rooms etc.', 'Sreedevi Pillai', 'MVP - Minimum Viable Product', 'mobility   mobile   facility management app   MVP - Minimum Viable Product   Facility Management App'),
(28, 'Blockchain', 'Farm2Fork', 'Farm to fork is an application that it is based in a specific use case of the concept of smart tracker. This application provides transparency and traceability to the process of Production and distribution of consumer goods   using Blockchain technology. In other words   the application allows the registry of every phase of the supply chain. It is also remarkable that this type of use case generates too much data that   usually   it is not processed. Because of that   the application also uses Big Data technology to exploit all the data generated in the phases of the supply chain.With this intention   the demo consist of emulating the process called farm to fork. Due to this   we will identity farm Products with a QR code. Then   using that identifier   we will record in the Blockchain ledger   all the stages through which pass the Product.', 'Maria Teresa Nieto  Francisco Honrubia  David Sanchezseco', 'MVP - Minimum Viable Product', 'blockchain   farm2fork   MVP - Minimum Viable Product'),
(29, 'Deep Learning', 'Fifth Dimension Cybersecurity', 'The Fifth Dimension platform fuses massive amounts of data from any collection source   in any format  \nstructured and unstructured. Using advanced deep learning artificial intelligence within a mass scale\ndata framework   the platform generates automated insights to produce accurate predictive intelligence.', 'Anshu Pillai', 'Product', 'deep learning   cyber security   fifth dimension   Product   Fifth Dimension Cybersecurity   Fifth Dimension Cyber security'),
(30, 'Deep Learning', 'Fifth Dimension Insurance', 'Fifthe Dimensions applies deep learning   the most advanced form of AI  to uncover the hidden value with the massive amounts of insurance data.The platform fuses telematic data with additional resources structured & unstructured including social media   insurance claims etc.Harnessing the power of deep learning   fifth dimension allows insurance companies to prevent accident before they happen   perform better underwriting & ultimately increases revenues & profitability.', 'Anshu Pillai', 'Product', 'deep learning   insurance   fifth dimension   Product   banking   Fifth Dimension Insurance'),
(31, 'Deep Learning', 'Fifth Dimension Retail', 'The fifth Dimension of Deep learning is the most advanced form of AI to uncover the hidden value with massive analysis of data.It allows retailers to predict changing trends   optimize inventory & alternatively increases revenue & profitabily.Fifth Dimensions fuses all the retailers available resources for structured and unstructured.', 'Anshu Pillai', 'Product', 'deep learning   retail   fifth dimension   Product   Fifth Dimension Retail   deeplearning'),
(32, 'Cloud computing', 'FogPanel based Cloud Management ', 'FogPanel   a comprehensive Cloud Service Management and Governance platform to Orchestrate   Manage   Monitor and Track Usage across your Hybrid Cloud environments. FogPanel allows enterprises and service providers to precisely control IT resource usage and yet allow finer user self-service to automate cloud resources from a central control system.', 'Raghu Pushpakath', 'Product', 'cloud computing   fogpanel based cloud management   Product   cloud'),
(33, 'Machine Learning', 'Food Wastage Prediction for Indigo Airlines', 'Predictive analysis done using Xpresso Engine to reduce wastage by forecasting customer demand using previous data', 'Chandrasekhar S', 'MVP - Minimum Viable Product', 'machine learning   ML   Food Wastage Prediction for Indigo Airlines   MVP - Minimum Viable Product   machinelearning'),
(34, 'Cyber security', 'Fort Scale', 'Fortscale is not just rules-engine. It has been designed from the ground up as a machine learning system that uses advanced computing and mathematics to detect abnormal account behavior indicative of credential compromise or abuse.', 'Praveenkumar Nair', 'Product', 'cyber security   fort scale   fortscale   Product   cybersecurity'),
(35, 'GIS Datathon', 'Geo-Mark', 'Geo Mark is a Web & Mobile Location Rating Solution with Geo Index.Individual Location Rating Through Data Analytics.\nComprehensive Comparison Reports For Rating Locations with Graphical data.Can be integrated with existing Real Estate Websites as an add-on.Can make use of social analytics to provide user specific search parameters with dynamic weightage.\nSingle buyers   property dealers   real estate websites   industries   commercial enterprises.\n', 'Arun Sreekumar   Jayadeep Jayakumar   Richu Joseph   Rishi Sasikumar   Manikantan Ravi   Lijo Vazhachariyil', 'MVP - Minimum Viable Product', 'gis datathon   geo mark   geomark   geo-mark   MVP - Minimum Viable Product   gis'),
(36, 'Machine Learning', 'Health care Assist', 'Customised chatbots using AI to help customers find the best providers in the location with their Contact no   Mail id with the customers rating also it shows the distance of the provider form the customer location using GPS. ', 'Chandrasekhar S Mohammed Sarfaras', 'MVP - Minimum Viable Product', 'machine learning   health care assist   chatbots   AI   artificial intelligence   gps   MVP - Minimum Viable Product   healthcare'),
(37, 'Mixed Reality', 'HoloLens based Room Designer App', 'Uses Mixed Reality and Hololens headgear to create Holograms to simulate an immersive shopping experience . It can create 3D holograms of Products in catalogue which can also be tried out in a particular room or color to check suitablity .', 'Romy JohnAnoop Ravi', 'MVC - Minimum Viable Concept', 'mixed reality   holo lens   hololens   hololens based room designer app   3d   MVC - Minimum Viable Concept   mixedreality   '),
(38, 'Machine Learning', 'ICE Platform based Anomaly Detection', 'It’s a UST - AI Platform which has an end to end components to design  Solve the AI related problems.', 'Chandrasekhar S', 'MVP - Minimum Viable Product', 'machine learning   ML   ICE platform   AI platform   artificial intelligence   MVP - Minimum Viable Product   ICE Platform based Anomaly Detection'),
(39, 'Machine Learning', 'IMS Helpdesk chatbots', 'Same chatbots customised to replace helpdesk and raise tickets to concerned departments to deal with IMS related queries', 'Chandrasekhar S', 'MVP - Minimum Viable Product', 'machine learning   ML   IMS helpdesk chatbots   chatbotss   MVP - Minimum Viable Product   helpdesk   chatbots'),
(40, 'Artificial Inteligence', 'INATA - Intelligent Algorithmic Trading Assistant', 'INATA - Intelligent Algorithmic Trading Assistant is an AI-based trading software. Algorithmic Trading is the process of performing financial trading using software. This is very prevalent in Western markets. Traditional Algorithmic Trading Software are inefficient and need significant human intervention. INATA augments traditional algorithmic trading with AI capability so that the algorithm can learn from historical domain data as well as function without human intervention. ', 'Kurien Thomas', 'MVP - Minimum Viable Product', 'artificial intelligence   AI   INATA -  Intelligent Algorithmic Trading Assistant   MVP - Minimum Viable Product   Trading Assistant'),
(41, 'Boots Ideathon', 'Intelligent chatbots for Boots UK', 'The idea is to have an Intelligent chatbots that interacts with the Customer   understands the issues and provides resolution steps based on the historic ticket details. It will either direct the customer to Self Service Catalogs  or provide steps to resolve by themselves based on previous historic information.', 'Jyothish Kumar', 'MVC - Minimum Viable Concept', 'boots ideathon   intelligent chatbots for boots uk   MVC - Minimum Viable Concept'),
(42, 'Artificial Inteligence', 'Intelligent Interpreters', 'Smart Interpreter designed to automate the process of read   interpret the unstructured regulatory documents to structured documents that helps to reduce the workforce and response time and minimize the legal complication.', 'Veena Raju and Team', 'MVC - Minimum Viable Concept', 'artificial intelligence   AI  Intelligent Interpreters   MVC - Minimum Viable Concept'),
(43, 'Analytics', 'Kognitios', 'Kognitios provides full text search capabilities   assisted with a graph of machine learned contextual information. This contextual information helps the user in two aspects   \n1) Users can use the contextual information to locate the content he is looking for \n2) Users are provided with a list of documents that describe more about the context. \nUser can use this to understand the context and its relations to other entities. It is a web application utilizing Stanford deepdive and Elastic search to deliver these capabilities. The contextual graph is created using supervised learning techniques. \nKognitios has a graph of entities connected by relationships and documents are connected to the graph via the machine learned relative strength of mentions of these entities.', 'Jibu  Anu Azeez', 'MVP - Minimum Viable Product', 'analytics   kognitios   MVP - Minimum Viable Product   text search   elastic search   machine learning   knowledge graph'),
(44, 'D3', 'Le VAINQUEUR', 'A voice-controlled interactive virtual assistant that a user can speak to or type in their query in natural language. The virtual assistant will try to help them achieve what they are looking for without the user having to navigate manually on a website. In the prototype   the team is planning to implement one of the most used features on the Anthem website - Provider finder. ', 'Syamlal Nair', 'Product', ''),
(45, 'Artificial Inteligence', 'Le VAINQUEUR\n Semantics- Intelligent Text Interpreter', 'Semantics is an intelligent interpreter that will help to extract metadata   impacted entities   topic magnitude and headlines    thus generating actionable insights and there by identifying the impacted domains and Products. Thus it can help alerting the people and business at the right time.\n', 'Syamlal Nair', 'Product', 'Artificial Inteligence   AI   Le VAINQUEUR\n Semantics- Intelligent Text Interpreter   MVP - Minimum Viable Product   natural language processing   nlp   virtual assistant'),
(46, 'Artificial Inteligence', 'Learn more', 'It help businesses to identify the deeper needs of the end users of their Product or service   especially when the business have large number (tens of thousands) of  and users in various demographics.', 'Anup Adhurkutty', 'MVC - Minimum Viable Concept', 'Artificial Inteligence   AI   learn more   MVC - Minimum Viable Concept'),
(47, 'Robotic Process Automation', 'Leave Balance', 'Fetch Leave Balance from ERP to Notepad', 'Shibu Stylus', 'MVC - Minimum Viable Concept', 'RPA   Robotic Process Automation   Leave Balance   ERP   MVC - Minimum Viable Concept   roboticprocessautomation'),
(48, 'Boots Ideathon', 'Machine Learning for Incident Ticket Classification', 'Applying machine learning with a multi-class classification algorithm can expedite and automate this process to a great extent. Power BI can be used to generate instant visual graphical report of the incidents. This can also be used to drill down the incidents to various levels. Natural Language queries can also be applied to Query the incident for a customized and faster reporting. \n', 'Mathew James', 'MVC - Minimum Viable Concept', 'Boots Ideathon   Machine Learning for Incident Ticket Classification    Natural Language Procesing   MVC - Minimum Viable Concept   NLP'),
(49, 'Machine Learning', 'Might', ' For Govt of Malaysia   collect trends and news from various sources (news sites   RSS feeds   social channels) related to technology trends   renewable energy automatically and classify into categories and sub categories ', 'Chandra', 'MVC - Minimum Viable Concept', 'Machine Learning   Might   Social   MVC - Minimum Viable Concept   Malaysia   Categorization'),
(50, 'Fintechathon', 'Mobile platform Application to Deliver GPS based tracking of Agents ', 'Mobile platform Application to Deliver GPS based tracking of Agents . This would help customer to overcomereduce  waiting period on collection repayment rounds.Google MAP APIs are faster ways to implement this in any platform . We used APIs called ‘Direction APIs’ for route marking    and Distance matric API for distance calculation (will be refreshed in each 30 seconds)   Server API for pushing location values to server.', 'Karthik Saminathan  Deepthi Binu  Unnikrishnan Narayanapillai  Arunkumar Nair', 'MVP - Minimum Viable Product', 'Fintechathon   Mobile platform Application to Deliver GPS based tracking of Agents   GPS   MVP - Minimum Viable Product   Mobility'),
(51, 'Mobility', 'NewsBytes App', 'Collates information relevant to a particular domain or vertical so as to allow all the employees of the Company to keep abreast of happening things in the their respective fields ', 'Sreedevi Pillai', 'MVP - Minimum Viable Product', 'Mobility   NewsBytes App   MVP - Minimum Viable Product   Mobile'),
(52, 'Machine Learning', 'NewsBytes Cateogories', 'UST Internal Collect news about UST customer   competitors   domains (from news sites   RSS feeds) we are interested in and automatically classify into categories and sub categories', 'Chandra', 'MVC - Minimum Viable Concept', 'Machine Learning   NewsBytes Cateogories   MVC - Minimum Viable Concept'),
(53, 'IoT', 'NFC Wall', 'Near Field Communication Scanner in phone  allows Product details to be scanned using a mobile application and  to move  those Products to cart     pay using mobile payment solutions and get them packed and ready to go at the counter or home delivered .', 'Sreedevi Pillai', 'MVP - Minimum Viable Product', 'IoT   internet of things   NFC Wall   near field communication   MVP - Minimum Viable Product   mobile   mobility'),
(54, 'Quality Assurance', 'NOSKRIPT', 'NOSKRIPT is a web platform to design test cases without any coding skill. In other words   it is a client server platform for distributed parallel execution on distributedCloud environments. Non-technical User can plotdesign the business flow and execute it on WebMobile devices. This platform supports iOSAndroid native apps and any web application. It has capabilities for built-in execution schedule   and reporting.', 'John Cherukara', 'Product', 'Quality Assurance   NOSKRIPT   Product   Cloud based   Web   Mobile   App   Mobility'),
(55, 'Xpresso Solutions', 'Omnichannel Customer Experience ', 'Customer experience tracker using twitter    economic times and e-mail to source feedback about the brand and even raise internal tickets directly to concerned department . It will also compare to nearest competitor and refreshes data collection every 10 minutes ', 'Anila Thomas', 'MVP - Minimum Viable Product', 'Xpresso Solutions   omnichannel customer experience   MVP - Minimum Viable Product   social'),
(56, 'Augmented Reality', 'Online Mobile Shopping (TMobile)', 'Application greets user with a phone menu with 3 phone model displayed. On saying  Show Model  gazing on any phone will give you details about the phone. To go back to the phone menu you could say  Show Phones  . In order to view the tablets menu user needs to say  Show tablets . Again to get the details you could gaze on tablet and say  show model . Verizon video', 'Anoop  Anju', 'MVC - Minimum Viable Concept  MVP - Minimum Viable Product  Product', 'Augmented Reality   AR   online mobile shopping (Tmobile)   MVC - Minimum Viable Concept  MVP - Minimum Viable Product   Product   retail   mobility'),
(57, 'Cyber security', 'Penetration Testing', 'Penetration test   or pen test   is an attempt to evaluate the security of an IT infrastructure.An effective penetration test will usually involve a skilled hacker   or team of hackers.The goal of penetration testing is to determine if unauthorized access to key systems and files can be achieved. If access is achieved   the vulnerability should be corrected and the penetration testing re-performed until the test is clean and no longer allows unauthorized access or other malicious activity.', ' Adarsh Nair', 'MVC - Minimum Viable Concept', 'cyber security   penetration testing   pen testing   MVC - Minimum Viable Concept   cybersecurity  '),
(58, 'IoT', 'Pill Dispenser', 'It will remaind you to take the pills at right time', 'Thomas K John', 'MVP - Minimum Viable Product', 'IoT   pill dispenser   MVP - Minimum Viable Product   Internet of things'),
(59, 'Artificial IntelligenceFintechathon', 'PROFIN', 'PROFIN is an Omni Channel Customer Engagement Platform which can provide better customer experience by providing banking Products and services virtually anywhere. It applies Natural Language Processing and Artificial Intelligence for document verification and loan approval and reduce the operational cost significantly. It increases the efficiency and transparency in the lending process.', 'Arjit Radhakrishnan  Dileep Das Kizhakkepalakath  Mansoor Veliyathunadu  Syamlal Nair', 'MVP - Minimum Viable Product', 'artificial intelligence   fintechathon   profin   MVP - Minimum Viable Product   omni channel engagement platform   NLP   natural language processing'),
(60, 'Mobility', 'QR Code Product Catalog App - NFC wall', 'QR Scanner allows Product details to be scanned using a mobile application and  to move  those Products to cart     pay using mobile payment solutions and get them packed and ready to go at the counter or home delivered .', 'Sreedevi Pillai', 'MVP - Minimum Viable Product', 'Mobility   QR Code Product Catalog App   NFC wall   qr scanner   MVP - Minimum Viable Product   Mobile   near field communication'),
(61, 'IoT', 'Queue Bursting for Retail Shopping', 'Gas station Automation directly by scanning car Number Plates so as to allow customer to directly pump gas without assistance  and payment though mobile solutions .', 'Thomas K John', 'MVC - Minimum Viable Concept', 'IoT   internet of things   Queue Bursting for Retail Shopping   gas station automation   MVC - Minimum Viable Concept'),
(62, 'Mobility', 'QuickPlay', 'A mobility usecase to pick and purchase the items available in a video.The user can buy clothings as worn by the Heros in the video where it further navigates to mcommerce app to purchase the similar shirt. Useful for Disney land. ', 'Sreedevi Pillai', 'MVP - Minimum Viable Product', 'mobility   mobile   QuickPlay   MVP - Minimum Viable Product   mobile'),
(63, 'Mobility', 'Ramp View', 'Mobile application that will capture data planeside and provide a real-time view of the operations by transmitting this data from the device to backend systems', 'Sreedevi Pillai', 'MVP - Minimum Viable Product', 'Mobility   ramp View   MVP - Minimum Viable Product   mobile'),
(64, 'Machine Learning', 'Retail Assistant chatbots', 'Customised chatbots using AI to help customers find Products in a retail environment . Could be Customised in online shopping as well using analytics', 'Chandrasekhar S', 'MVP - Minimum Viable Product', 'Machine Learning   ML   Retail Assistant chatbots   AI   artificial intelligence   MVP - Minimum Viable Product'),
(65, 'Blockchain', 'Retail Block chain', 'Blockchain technology is set to make positive changes in the world of luxury commerce   by dealing with its biggest problem   counterfeit. Blockchain technology can tackle the problem of fake goods in the luxury sector. They are achieving this by creating a secure registry which tracks who owns designer Products. The database holds everything a consumer will require to determine whether the Product they are about to purchase is actually genuine. ', 'Nikhil Krishna', 'MVP - Minimum Viable Product', 'Blockchain   retail block chain   MVP - Minimum Viable Product'),
(66, 'Robotic Process Automation', 'RPA Usecase', 'Demonstration is for “Importing salesforce contacts from excel spread sheet”.The work flow is designed in RPA tool to automatically upload contacts from excel spread sheet to a salesforce account.', 'Shibu Stylus', 'MVC - Minimum Viable Concept', 'rpa   robotic process automation   rpa usecase   excel'),
(67, 'Mobility', 'SBI Digital Banking App', 'Bank Mobile Application done for India s largest public sector bank ', 'Abhilash Krishnan  Divyamol Salimkumar', 'Product', 'Mobility   mobile    SBI Digital Banking App   Product'),
(68, 'Digital Enterprise Apps', 'Scion Continuous Integration Platform', 'Scion is a hybrid continuous integration and continuous (CICD) delivery tool. Scion helps project teams to initiate CICD process without much difficulty and view the quality improvement through Scion dashboard. Project teams could take instant or quick builds as well as schedule the builds for a future date using a scheduler module.', 'Ranjith M Nair', 'MVP - Minimum Viable Product', 'Digital Enterprise Apps   Scion Continuous Integration Platform   MVP - Minimum Viable Product'),
(69, 'Bussiness Model', 'Six Sigma', 'Transforming IT service engagements into long-term strategic partnerships is one of the biggest challenge faced by India s 75 billion IT Services Industry today. In the presentation   we propose a two-level approach in tackling this by citing the example of Insight - An IIOT Product development engagement of UST Global with a major fortune 500 conglomerate.\n\nWe take a look at the business models of the client to understand key segments of their business models   how we build our business models around it and examples of how we deliver value to those segments. The presentation also provides a blueprint for replicating this model across other accounts through actionable steps that can be taken to get started.', 'Vishnu Kasiviswanathan   Mithun Manohar', 'MVC - Minimum Viable Concept', 'bussiness model   six sigma   MVC - Minimum Viable Concept   businessmodels'),
(70, 'Embedded', 'Smart Sthethescope', 'Smart Stethescope is a healthcare Asset    a digital Stethescope which can diagonise Heart Rythms with Visualization.  It includes   \nDeep Learning Application- Extracts Heart sound   Murmur and Integrated EKG\nComprehensive reporting meeting medical standards \nRecord and Analyze the heart sound   murmur and EKG on device and app\n\n', 'Nivashini Muthukrishnan ', 'Product', 'smart stethoscope smart sthethoscope smart stethescope smart sthethescope embedded deep learning deeplearning product healthcare'),
(71, 'IoT', 'Smarter Home Automation', 'Home Automation through calling a particular phone number whose keypad response is code for a particular task . Eg. 1. Switch Lights on 2. Switch Fan on ', 'Thomas K John', 'MVC - Minimum Viable Concept', 'IoT   Smarter Home Automation   internet of things   home automation    MVC - Minimum Viable Concept'),
(72, 'IoT', 'Smarter Parking', 'It will allocate the parking facility automatically', 'Thomas K John', 'MVC - Minimum Viable Concept', 'IoT   Smarter Parking   MVC - Minimum Viable Concept   transport   internet of things'),
(73, 'IoT', 'Smarter Retail Isle', 'Beacon based tag to know exactly what are items kept on a particular shelfrack', 'Thomas K John', 'MVC - Minimum Viable Concept', 'IoT   smarter retail isle   MVC - Minimum Viable Concept   beacon   internet of things'),
(74, 'Social', 'Social MCI Dashboard for Singapore Government', 'Mapping Social Media Trend to form a real time assesment of perception of brands among people and areas of concern adapted for Singapore Govt. to gauge public reaction', 'Deepa Sobhana', 'MVP - Minimum Viable Product', 'social   Social MCI Dashboard for Singapore Government. MVP - Minimum Viable Product   Singapore'),
(75, 'Social ', 'Social Media Listening and Competitor Intelligence', 'Mapping Social Media Trend to form a real time assesment of perception of brands among people and areas of concern', 'Deepa Sobhana', 'MVP - Minimum Viable Product', 'Social  Social Media Listening and Competitor Intelligence   MVP - Minimum Viable Product'),
(76, 'Xpresso Solutions', 'Sofia', 'chatbots which is used for sheduling the meeting and creating a report based upon the conversation done in the bot', 'Pushpal  Joydeep', 'MVP - Minimum Viable Product', 'Xpresso Solutions   sofia   MVP - Minimum Viable Product   chatbots   nlp   natural language processing'),
(77, 'Fintechathon', 'Subprime Lending Defaulter Prediction System', 'Currently the Subprime lending is providing accounting to the customer scores of heshe having. Our Model is to predict the defaulter’s in subprime lending market of small and medium customers. Identifying variables relevant to Provident lending market and use the same to build Historical data to make a training model   which can predict the possibility of customer comes under defaulter and no-defaulter list.', 'Sajeesh Gopalan   Bipi Mohan   Kannan Prasad   Shinto Kunnanmathew', 'MVP - Minimum Viable Product', 'Fintechathon   Subprime Lending Defaulter Prediction System   MVP - Minimum Viable Product   accounting   finance'),
(78, 'Mobility', 'Tele-Fashion Consultant Concept Demo', 'Video Calling integrated tele fashion consultant concept which can also be used to book appointments both face to face and tele-appointment . It can also show location based availablity of fashion consultants and their specialisation . ', 'RajaLakshmi Baburajan', 'MVC - Minimum Viable Concept', 'Mobility   mobile   Tele-Fashion Consultant Concept Demo   MVC - Minimum Viable Concept   chatbots'),
(79, 'Mobility', 'Telemedicine App Demo', 'Video Calling integrated medical consultation intented for rural areas in India which may proper health services .  ', 'Sanoj Parethu', 'MVP - Minimum Viable Product', 'Mobility   mobile  telemedicine app demo   MVP - Minimum Viable Product   healthcare'),
(80, 'MongoDB Techathon', 'Test MongoDB with Jmeter for Automated Performance', 'Integrates JMeter with Mongo DB for performance testing directly on the DB so that Non functional requirements and effectiveness of scaling   availability can be validated before affects real Production users. This is innovative and can be extended with other performance tools and can be automated if required', 'Ranjan Kumar Singh', 'MVP - Minimum Viable Product', 'MongoDB Techathon   Test MongoDB with Jmeter for Automated Performance   MVP - Minimum Viable Product   automation'),
(81, 'GIS Datathon', 'Trade Envisage', 'Trade envisage - forecast and depiction of future trade\nDerive the facts and insights with landmarks  rich data information   that would make an business opportunity\nIntelligent solution to forecast the supply and demand of trade – Pharmaceutical retailer\nDisease trends – predictive model to generate a knowledge base on the demand of the pharmacy Products based on epidemics trends data.\nSupply chain excellence is a powerful competitive advantage.\nBetter society.', 'Surej Anwar   Noora Japher   Rukmani Selvaraj   Gopikrishnan Dhanasekaran', 'MVP - Minimum Viable Product', 'GIS Datathon   Trade Envisage   trading   MVP - Minimum Viable Product   finance   healthcare   pharmacy   pharmaceutical'),
(82, 'Innovation POD', 'Trade Finance Product Development', '', 'Gokul Alex  Sachith Sebastian', 'MVP - Minimum Viable Product', 'Innovation POD   Trade Finance Product Development   trading   MVP - Minimum Viable Product   '),
(83, 'Blockchain', 'trUSTCoin', 'trUSTcoin is a token developed over a Blockchain network with the purpose of award the employees with some rewards. The token is intended to be awarded on special occasions   as the organization of a hackathon or the referral of new internsemployees.The awarded tokens can be then spent on the available rewards on the system. These rewards will serve as non-monetary gratification for the employees. The rewards could be for example cinema tickets   a dinner or massage sessions.', 'Maria Teresa Nieto  Francisco Honrubia  David Sanchezseco', 'MVP - Minimum Viable Product', 'Blockchain   trUSTCoin   trUST Coin   MVP - Minimum Viable Product'),
(84, 'Mobility', 'uDispatch', 'This Platform fills the whitespace in enterprise mobility as a technology agnostic\nintegrated front end application. There is no pre-builtpre-packaged enterprise application\navailable on the market today which is “back-end” agnostic.', 'Anil Anand', 'MVP - Minimum Viable Product', 'Mobility   mobile   uDispatch   MVP - Minimum Viable Product   application   apps'),
(85, 'IoT', 'Ur Safe', 'Women safty Mobile app which is used to call Commisioner of police on emergency situation. And police can track the place ', 'Thomas K John', 'Product', 'IoT   internet of things   Ur Safe   Mobile app   Product   women safety'),
(86, 'Infrastructure Management', 'UST Maya Robotic Process Automation', 'Virtual Engineer for resolving IMS related issues and tickets ', 'Muraleekrishnan Nair', 'MVP - Minimum Viable Product', 'Infrastructure Management   ust maya robotic process automation   MVP - Minimum Viable Product   RPA'),
(87, 'Blockchain', 'Vehicle Management System', 'Supply chain management system using blockchain which adds the finger print of a vehicle to track down the details.', 'NikhilAbhilashSarangGokulShanAldaAgnus', 'MVP - Minimum Viable Product', 'Blockchain   vehicle management system   MVP - Minimum Viable Product   transport   transit   finger print'),
(88, 'Artificial Inteligence', 'VERA', 'Vera is a personal shopping assistant that\nhelps retail customers explore Products in\ncontextual. AI driven assistant that helps\nthem imagine   play and tinker with ideas.', 'Gokul Alex  Ankit', 'MVC - Minimum Viable Concept', 'Artificial Inteligence   AI   VERA   shopping assistant   retail   MVC - Minimum Viable Concept   chatbots'),
(89, 'Fintechathon', 'VFBot', 'In today’s environment   Auto finance lending markets continue to experience tremendous change in terms of credit performance and risk assessment for different types of borrowers. New and innovative strategies are required to align lenders for future success and growth in terms of credit providers and auto lenders. In order to make the accountable and long term relationship between customers and credits providersauto dealers   we will propose an Artificial Intelligence Bot VFBot to generate High Conversion Leads for the Vehicle Finance Agents (auto dealers and credit providers).', 'Balachandar Raju   Abhishek Kumar', 'MVP - Minimum Viable Product', 'Fintechathon   VFBot   finance   MVP - Minimum Viable Product'),
(90, 'Fintechathon', 'Virtual Payment', 'The thought is based on the fact that customer who is focused is an organization dealing with financing non standard customers. So there is a high chance of customers defaulting in repayments and getting into defaulters list. This will impact the rating of customers. So the idea thought of a mechanism by which customer get another chance to keep themselves in good customer list and organization can make some extra money.The solution is to have 3 (a fixed number of virtual payment) along with normal payment schedule. If a person is missing any of the schedule he can avail this virtual payment option so that he can pay later but will not be part of defaulters list. This option involve some additional payments which can help organization to make some extra revenue. as well.', 'Satya Narayana Das  Ganesh Krishnan  Dileep Narayanan', 'MVP - Minimum Viable Product', 'Fintechathon   Virtual Payment   finance   MVP - Minimum Viable Product'),
(91, 'Augmented Reality', 'Virtual Shelf arrangement (HEBWalmart)', 'The app names as HEB. When we launch the app an initial screen with a small shelf will appear   on tapping the shelf it will generate a bigger shelf. On saying   show menu  the app will show the list of 3 Product on right side of the shelf. User can tap on a Product   then the Product will be generated next to the list   on tapping the Product for the second time it will start floating with the user head movement. The user can gaze and tap to place the Product on the shelf.', 'Anoop  Anju', 'MVC - Minimum Viable Concept  MVP - Minimum Viable Product  Product', 'Augmented Reality   AR   Virtual Shelf arrangement (HEBWalmart)   MVC - Minimum Viable Concept  MVP - Minimum Viable Product   Product   retail'),
(92, 'Xpresso Solutions', 'Xpresso - Commerce', 'Personalized e-commerce solution which provides an interface for users to interact with the system in natural language and enhance their shopping experience.Currently implemented it on Facebook messenger   but have the flexibility to extend it to other platforms like Skype.', 'Mandira', 'MVP - Minimum Viable Product', 'Xpresso Solutions   Xpresso  Commerce   MVP - Minimum Viable Product   natural language processing   NLP');

-- --------------------------------------------------------

--
-- Table structure for table `login`
--

CREATE TABLE `login` (
  `username` varchar(20) NOT NULL,
  `password` varchar(20) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

--
-- Dumping data for table `login`
--

INSERT INTO `login` (`username`, `password`) VALUES
('admin', 'admin');
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
